### ISSUE TITLE
Updating include does not update output using Eleventy dev server

### ISSUE THREAD

**Issue by carpelli** [noelforte/eleventy-plugin-vento#38] opened 2024-10-15 12:12 UTC
### Steps to reproduce

Run `npx @11ty/eleventy --serve`
Modify a Vento template file `include.vto` included by `{{ include 'include.vto' }}`

### Expected behavior

The template is rerendered with the updated included template

### Actual behavior

Site is rebuilt but the output doesn't change

### Plugin version

3.0.2

### Eleventy version

3.0.0

### Additional information

Basically #34, but this time for the includes

**Comment by noelforte** [comment] 2024-10-15 16:51
I'll take a look later today. Just for context, are you using `--serve --incremental` or just `--serve`?

**Comment by carpelli** [comment] 2024-10-15 17:16
I’m just running `—serve`

El dt, 15 oct. 2024 a les 18:52 Noel Forte ***@***.***> va
escriure:

**Comment by noelforte** [comment] 2024-10-16 03:41
No, you're good, I was able to get this reproduced, just need to dig a bit more on how to patch this in a way that preserves caching functionality for speed while also clearing things where appropriate. Then I also should write more unit tests that cover this, becuase right now caching and `--serve` doesn't have any test coverage. 

On a somewhat related note, issues like this will be much easier to triage once I get #21 finished.

**Comment by noelforte** [comment] 2024-10-21 19:13
Possible opportunity to handle this upstream so we can do it right since Vento doesn't provide any information about associations of includes to their dependents. The easy way to handle cache during development would be to "clear-all-on-save" but that's not super conservative.

I'm going to raise this upstream to see what potential options there are for "smart caching" but in the meantime I can implement a hotfix that clears the cache on every save as a holdover.

**Comment by noelforte** [comment] 2024-10-22 21:53
@carpelli A fix for this is out in `v3.0.3-next.0` that clears Vento's cache completely on **every** Eleventy run. It's a bit of a brute-force solution and ideally I'd like something a bit more nuanced, hence the pre-release.

I've opened a request upstream at: https://github.com/ventojs/vento/issues/78 to see about retrieving associated files from Vento so I can selectively clear the cache instead of wiping everything out. How that resolves will dictate next steps here. Thanks!

**Closed** 2024-10-24 23:27 UTC
Labels: bug, upstream
